name: Release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: |
          go mod download
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      - name: Perform release
        run: |
          go mod tidy
          curl -sL https://git.io/goreleaser | bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}